# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96baddd7887c3bdff9756d3b7874afd23736a2bbf459c56029ef4e3c5448b2a0bd0a192552ad34d7b8609e771cee094b965cc862c8b9aca125ee75a1332abfa8

test:
  secret_key_base: 44056961965af525f8bf5994e98af780de7843a0eef281a752bc261a911b90530865b929ee16bb2a7bc3c1d1a23415c3840001c240b9de12242e9045ffe25034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
